### ISSUE TITLE
文档请求

### ISSUE THREAD

**Issue by pzzxqj** [chenlin014/xingzheng#1]
请问作者是否能添加详细的文档，包括按键映射等。

**Comment by chenlin014** [comment]
感谢您的好评！
抱歉让您等了这么久。
您说的没错，我确实需要提供文档和说明，而这一直都是我所忽视的。
我打算在完成现阶段的开发整理后开始写。

您提到了「按键映射」，您能说得更详细一些吗？

**Comment by pzzxqj** [comment]
作为一个郑码使用者，我很高兴看到新的并击方案的产生。我试用了rime方案。

似乎字根是键盘左右两侧对称分布，对应的4位数字从左到右对应小拇指到食指，1代表第一排，2代表第二排，3代表第一排和第二排一起按。但我不并不能顺利的打字。我想知道字根的构成字时候规则是什么。左右两手如何按键。比如“你”字。

**Comment by chenlin014** [comment]
### 改名
我想先说一下名称上的变更。我决定把连击版和并击版分成两个方案，连击版保留「新郑」这个名字，而并击版则改名为「有熊」。

新郑：https://github.com/chenlin014/rime-xingzheng
有熊：https://github.com/chenlin014/rime-youxiong

### 设置问题
回到您的问题，我想问题可能出在多击模式上。默认设置用的是多击模式，但我其本上只用单击模式，所以我一直都没有发现，由于其它地方的改动，这个模式已经不能用了，不过我已经把它更新了，在我这边是能用了，如果您那边还是不行，请通知我。
别外，默认的字典是繁体字典，您可以把字典改成youxiong-jt。

### 方案说明
关于并击方案，您的观察没错，它确实是左右对称的，一只手负责一个字根，一击两根。一字最多四根，超过四根的字只取首尾四根，因此一字最多而要两击。部分常用字可通过简码一击完成。

除开大拇指，其除四根手指能按八个键。每个字根都对应这八键的一个子集，我称之为按式。
每个按式可以有两个字根， 一个主根，一个副根，两者由副根键区分。

### 键盘布局
这个方案原本是为[Plover](https://plover.wiki/index.php/Plover_Wiki)设计的，有很多地方我是仿照的[Stenotype](https://plover.wiki/index.php/Steno_layouts_and_supported_languages)。

![youxiong-layout](https://github.com/user-attachments/assets/c85d8fbf-07ff-4986-9082-e818f7bb1650)

### “你”字的输入方法
说回您的问题，“你”字的简码是左“亻”，用左手按出“亻”的按式，同时用右手按简码键就能打出“你”这个字。
亻的按式：
--#-
-#--
(左手)

您也可以打出“你”字的完整编码。“你”这个字我是拆成了“亻”和“尔”，而“尔”又被拆成“亇”和“八”，“亇”和“个”同属于“竹“这个字根，所以”你“这个字的编码是”亻竹八“。第一击打“亻竹”，第二击打“八”。
竹（竹是𠂉的副根）：
--#-
---#
副
（右手）

八：
--#-
---#
（左手）

### 最后
我不擅长写东要，可能解释的不好，有什么问题请告诉我。

**Comment by chenlin014** [comment]
# 当前的按式配置
我对这个配置不是很满意，我想找时间重新编排一下。

![image](https://github.com/user-attachments/assets/ed353d29-64bd-4953-81bf-d2b5e7c07e67)
![image](https://github.com/user-attachments/assets/e501ed40-b293-41f0-a893-18071fd72e0f)

**Comment by pzzxqj** [comment]
感谢你的回复，根据你的指导成功通过简码的方式输入”你“。

但是在通过完整编码的方式输入”你“字时，按照“第一击打“亻竹”"，松手后，直接上屏的结果是”口丿第“。请问这是什么问题？

另外，有熊也是个能反应新郑的好名字。

**Comment by chenlin014** [comment]
谢谢，我是因为喜欢熊所以才会对这一点印象深刻。

说回正题。我打开了单击自动上屏（单击模式），我打「亻竹」打出的也是「口丿第」，所以我觉得这可能是设置文件的问题，您能提供您的schema文件的内容吗？

另外，我发现我所提供的按式图是我修改到一半的结果，有些地方与库中的字典并不相符。

**Comment by chenlin014** [comment]
我发现我所提供的按式图是我修改到一半的，有些地方与库中的字典并不相符。

**Comment by pzzxqj** [comment]
我使用是仓库中原始的`schema`文件，只是使用了简体字典。

**Comment by chenlin014** [comment]
我想先介绍一下有熊的三个模式。

有熊的三个模式是，多击模式，单击模式，和简码模式。左右大内键（C和M）在这三个模式中有不同的职责。

在多击模式下，一般编码不会自动上屏，在最后一击中按完成键（左大内）可使其上屏。

在单击模式下，每一击都会自动上屏，连成键（左大内）可用来避免上屏。

在上述的两种模式中，右大内键都是简码键，用来标明此击为简码，需一击上屏。

在简码模式下，每一击都默认为是简码，并一击上屏。左大内可用来输入单击字，右大内可用来以完整编码输入多击字。

回到您的问题，请您告诉我schema中设置的模式是那一个。

**Comment by pzzxqj** [comment]
```yaml
# Rime schema
# encoding: utf-8

schema:
  schema_id: youxiong
  name: 有熊輸入法
  version: '0.4'
  author:
    - 陈林 <1chen0bryan@gmail.com>
  description: |
    并击形码输入法
  dependencies:
    - luna_pinyin
    - pinyin_simp

switches:
  - name: ascii_mode
    reset: 0
    states: [ 中文, 拉丁 ]
  - name: full_shape
    states: [ 半角, 全角 ]
  - name: ascii_punct
    states: [ 。，, ．， ]

engine:
  processors:
    - ascii_composer
    - recognizer
    - chord_composer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - script_translator
    - reverse_lookup_translator
  filters:
    - uniquifier

chord_composer:

editor:
  bindings:
    BackSpace: back_syllable

speller:
  alphabet: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
  auto_select: false
  auto_select_unique_candidate: false

translator:
  # 正體字典
  dictionary: youxiong-jt
  # 简体字典
  # dictionary: youxiong-jt
  enable_user_dict: false

reverse_lookup:
  dictionary: luna_pinyin
  # dictionary: pinyin_simp
  prefix: "`"
  tips: 〔拼音〕
  preedit_format:
    - xform/([nl])v/$1ü/
    - xform/([nl])ue/$1üe/
    - xform/([jqxy])v/$1u/

punctuator:
  import_preset: symbols

key_binder:
  import_preset: default

recognizer:
  import_preset: default
  patterns:
    reverse_lookup: "`[a-z]*'?$|[a-z]+'$"

__patch:
  # 鍵盘布局
  - youxiong-options:/use_qwerty_layout
  #- youxiong-options:/use_dvorak_layout
  #- youxiong-options:/use_colemak_layout
  # 標點符號
  - youxiong-options:/punc_chord
  # 雙擊模式
  - youxiong-options:/two_stroke_mode
  # 單擊模式
  #- youxiong-options:/one_stroke_mode
  # 簡碼模式
  #- youxiong-options:/brief_mode

```
